openapi: 3.0.0
info:
  version: first version
  title: サンプル Api
paths:
  'jref#commentator_ua': ./paths/user_data_api.yaml
  '/console/api/v2/module/base/{base_id}/{detail_id}':
    parameters:
      - name: base_id
        in: path
        description: base id
        required: true
        schema:
          type: integer
          format: int64
      - name: detail_id
        in: path
        description: detail id
        required: true
        schema:
          type: integer
          format: int64
    get:
      tags:
        - console_api
      summary: 基本設定を取得(Get basic settings)
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                type: object
                parameters:
                  jpn:
                    type: object
                    parameters:
                      title:
                        type: string
                        description: タイトル
                example:
                  jpn:
                    title: タイトル
    post:
      tags:
        - console_api
      summary: 基本設定を保存(Save basic settings)
      requestBody:
        content:
          application/json:
            schema:
              type: object
              parameters:
                jpn:
                  type: object
                  parameters:
                    title:
                      type: string
                      description: タイトル
              example:
                jpn:
                  title: タイトル
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: ''
