parameters:
  - name: base_id
    in: path
    description: base id
    required: true
    schema:
      type: integer
      format: int64
  - name: detail_id
    in: path
    description: detail id
    required: true
    schema:
      type: integer
      format: int64
